### ISSUE TITLE
You Are The One Who Made AntiFly Correct

### ISSUE THREAD

**Issue by CraftingMania** [PocketMine-Developers/FlyCommand#1]
title says it all

**Comment by CraftingMania** [comment]
sorry i had to delete the respiratory because no readme or licesne or author please if you the one who made it tell me here

**Comment by TahaTheHacker** [comment]
he's Martin77Epic xD

**Comment by Martin77Epic** [comment]
Hi

**Comment by AmiroEmad** [comment]
want to chat go to http://mcrafters.ml it has been improved
